
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='borgcube',
    version='0.0.1',
    description='backup server for borgbackup with ssh key management, quotas and periodic reminders',
    python_requires='>=3.7',
    author='Fina Wilke',
    author_email='code@felinira.net',
    license='AGPL-3.0-or-later',
    entry_points={"console_scripts": ["borgcube = borgcube.borgcube:main"]},
    packages=['borgcube', 'borgcube.backend', 'borgcube.frontend'],
    package_dir={"": "."},
    package_data={},
    install_requires=['atomicwrites==1.*,>=1.3.0', 'colored==1.*,>=1.4.2', 'peewee==3.*,>=3.13.1', 'pyyaml==5.*,>=5.3.0', 'sshkeys==0.*,>=0.5.0'],
)
