from enum import Enum


class RemoteCommandType(Enum):
    BORGCUBE_COMMAND_SHELL = 'BORGCUBE_COMMAND_SHELL'
    BORGCUBE_COMMAND_BORG_SERVE = 'BORGCUBE_COMMAND_BORG_SERVE'


class AuthorizedKeyType(Enum):
    USER = 1
    USER_BACKUP = 2
    REPO_APPEND = 3
    REPO_RW = 4
    ADMIN_IMPERSONATE = 5


class LogOperation(Enum):
    CREATE_REPO = 1
    DELETE_REPO = 2
    SERVE_REPO_BEGIN = 3
    SERVE_REPO_LOG = 4
    SERVE_REPO_SUCCESS = 5
    SERVE_REPO_ABORT = 6
    CHANGE_REPO_QUOTA = 7
    CHANGE_REPO_SSH_KEY = 8
    CREATE_USER = 9
    DELETE_USER = 10
    CHANGE_USER_QUOTA = 11
    CHANGE_USER_SSH_KEY = 12
    CALC_QUOTA_BEGIN = 13
    CALC_QUOTA_END = 14
